### ISSUE TITLE
Circular use of feature generator and data pool generator

### ISSUE THREAD

**Issue by viviankou** [sfu-natlang/glm-parser#21]
A data pool generator is constructed using feature generator: fgen is passed in data_pool constructor
A feature generator is constructed using sentences: sentence is passed in feature_generator constructor
Need to get rid of this circular dependency, so that data_pool can be created without using fgen.

**Comment by anoopsarkar** [comment]
Let us solve this by not having sentence as an argument to the feature generator.

So feature generation will not get an index into the sentence class but rather get the word and postag as strings: `xi-word, xi-pos, xj-word, xj-pos`

**Comment by Travelinglight** [comment]
Here's another solution:
Instead of having sentence as an argument of feature generator's init function (`def _init_(self, sent):`), we can have the two members of sentence, word_list and pos_list, as arguments (`def _init_(self, word_list, pos_list):` ). And other member functions feature generator could remain the same.

The reason to use this solution is:
1. xi-word, xi-pos and xi-index are dependent variables. If we have all those things in the arguments, the function call would be very long. For example, the get_unigram_feature function would have 9 arguments. What's more, in the get_in_between_feature function, the head_index and dep_index is actually useful.
2. Feature generator need the word_list and pos_list to compute five_gram_word_list. If sentence doesn't give feature generator the word_list and pos_list, it will have to compute five_gram_word_list itself.

So I suggest we take this solution. Instead of using the whole sentence object to initialize feature generator, can we use word_list and pos_list to initialize it?

**Comment by anoopsarkar** [comment]
Yes, this is better but maybe we can generalize it a bit more. Different feature generators can have different requirements so we should have a solution where the feature generator can ask for certain "keys" say "word_list" and "pos_list" and `data_pool.py` can create a dictionary which will contain such keys. The data reader in `data_pool.py` knows which columns correspond to the right "keys". The interface is common across all feature generators: simply a dictionary, but it can demand different keys. The basic requirement is a word list and a postag list.

**Comment by anoopsarkar** [comment]
is this solved? can we close this issue?

**Comment by viviankou** [comment]
Yes, this is solved.
