### ISSUE TITLE
data_pool & fgen design

### ISSUE THREAD

**Issue by Travelinglight** [sfu-natlang/glm-parser#22]
This is my design:
-----------------------------------Sean's part-----------------------------------
DataPool read two files when initiated: 
config file: n lines, each line a field name
data file: n columns, each column corresponds to the field name specified in config file
They are both specified in command line arguments.

DataPool read the config file and create a field_name_list. In data file, each time an empty line is read, DataPool pack the columns of data into a list (a list of lists) and give it to Sentence along with field_name_list as arguments of init function.

Sentence should have another function (e.g. `fetch_column(self, field_name)`) to fetch a column of data according to the field_name.

-----------------------------------Kingston's part------------------------------
1. The field_names of the columns needed for a feature generator is hard-coded (in care_list) in its init function. 
2. Sentence reads f_gen.care_list and knows what columns does f_gen care about.
3. Sentence fetches the data columns and pack them with a list.
4. Sentence calls f_gen.init_resources function to give the f_gen the data columns.
5. Thus f_gen gets all it wants from Sentence without having Sentence as its init function's argument.

----------------------------------Branch merge order change------------
In this design, my branch should be merged with Sean's branch, or it doesn't work. After our two branches are merged and debugged, we can merge Vivian's branch.

So what do you think about this design? If you get a better idea, please comment on this issue : )
I have changed code on my branch (data_pool_fgen_clean). Now the english_1st_fgen works fine.

**Comment by thefantasticdron** [comment]
When we create a sentence object, we currently pass an `edge_set dict` as one of our parameters which contains edge information for the construction of a dependency tree. In the function `get_data_list` in the `DataPool` class, we can construct each `edge_set dict` easily since the `get_data_list` function is specialized for only Penn2Malt data formats. However, if we wish to generalize data reading for any data format, it is harder to construct the `edge_set dict` since other data formats may place information about the dependency tree in different columns.

My question is, then, should I continue to construct the `edge_set dict` for each tree in `get_data_list` or construct it in another function elsewhere?

**Comment by Travelinglight** [comment]
I have an idea. You can write a function `construct_edge_set(HEAD_list, DEPREL_list)` in Sentence, and call this function to construct the edge set in the init function. Since you already have a function to fetch a column by it's field_name, you can get HEAD and DEPREL easily.

The problem is, users may name the columns differently. For example, they may call the HEAD column DEP. However, HEAD and DEPREL are standard names in CoNLL format. If users follow the field_name standard, they won't get into trouble.

Another option is, to specify the HEAD and DEPREL in that config file by two integers, indicating which columns are they.

**Comment by thefantasticdron** [comment]
That's a good idea. I think I'll do the last option.

**Comment by anoopsarkar** [comment]
Is this done? Can we close this issue?
